### ISSUE TITLE
create-model.py error

### ISSUE THREAD

**Issue by qamar-abbas-sys** [NanoNets/nanonets-ocr-sample-python#5]
when i run create-model.py then it gives error.
Traceback (most recent call last):
  File "./code/create-model.py", line 11, in <module>
    model_id = json.loads(response.text)["model_id"]
KeyError: 'model_id'

which api_key i need to copy in code. i copy api key from nannets api_keys tab.

**Comment by Janis-Leuenberger** [comment]
[NanoNets](https://app.nanonets.com/#/keys ) This is the website you get your API Key from.

In case you are using windows, there might be a problem with the system variables. This will result in a NONE-Object and the code crashes at line 11.

Instead of using `export`, you must use `set` as this is the windows equivalent.

If you use `setx`(the permanent version of `set`), make sure your shell has administrator permissions.

**Comment by rushabhnagda11** [comment]
@Janis-Leuenberger thanks for the help here. Appreciate it.
